# mise configuration for Unity 2022.3 compatible .NET SDK
[tools]
# Unity 2022.3 requires .NET 6.0 SDK for development
"vfox:version-fox/vfox-dotnet" = "6"

node = "24"
"npm:openupm-cli" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@upstash/context7-mcp" = "latest"

[tasks.lint]
run = """
mise lint-dotnet && mise lint-dotnet-editor && mise lint-udonsharp
"""

[tasks.lint-dotnet]
description = "Run .NET code analysis for Unity scripts"
run = """
dotnet build Assembly-CSharp.csproj
"""

[tasks.lint-dotnet-editor]
description = "Run .NET code analysis for Unity Editor scripts"
run = """
dotnet build Assembly-CSharp-Editor.csproj
"""

[tasks.lint-udonsharp]
description = "Run UdonSharp specific linter"
run = """
dotnet run --project Tools/UdonSharpLinterCLI/UdonSharpLinterCLI.csproj -- Assets --exclude-test-scripts
"""
