# mise configuration for Unity 2022.3 compatible .NET SDK
[tools]
# Unity 2022.3 requires .NET 6.0 SDK for development
"vfox:version-fox/vfox-dotnet" = "6"

node = "22.17.0"  # LTS version (Jod)
"npm:openupm-cli" = "latest"
