# mise configuration for Unity 2022.3 compatible .NET SDK
[tools]
# Unity 2022.3 requires .NET 6.0 SDK for development
"vfox:version-fox/vfox-dotnet" = "6"

node = "24"
"npm:openupm-cli" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@upstash/context7-mcp" = "latest"

[tasks.lint]
description = "Run Unity C# code analysis with Roslyn Analyzers"
run = "powershell -ExecutionPolicy Bypass -File unity-roslyn-lint.ps1"

