name: Code Analysis

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore --configuration Release
    
    - name: Run code analysis
      run: |
        dotnet format --verify-no-changes --verbosity diagnostic
        dotnet build --no-restore --configuration Release /p:TreatWarningsAsErrors=true
    
    # Optional: Run SonarCloud analysis
    - name: SonarCloud Scan
      if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=your-project-key
          -Dsonar.organization=your-organization
          -Dsonar.sources=Assets/
          -Dsonar.exclusions=**/*.meta,**/Packages/**,**/Library/**
          -Dsonar.cs.opencover.reportsPaths=**/coverage.opencover.xml